'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle

tommy = turtle.Turtle()
tommy.shape('turtle')
tommy.color('black')

tommy.right(90)
tommy.forward(100)
tommy.forward(20)
tommy.left(90)

tommy.begin_fill()
tommy.color('red')
tommy.forward(50)
tommy.left(45)
tommy.forward(10)
tommy.left(90)
tommy.forward(10)
tommy.left(45)
tommy.forward(100)
tommy.left(45)
tommy.forward(10)
tommy.left(90)
tommy.forward(10)
tommy.end_fill()
tommy.left(45)
tommy.forward(45)
tommy.begin_fill()
#draw hilt
tommy.color('saddlebrown')
tommy.right(90)
tommy.forward(60)
tommy.left(90)
tommy.forward(10)
tommy.left(90)
tommy.forward(60)
tommy.end_fill()
tommy.penup()
tommy.left(180)
tommy.forward(60)
tommy.pendown()
tommy.begin_fill()
#draw end of sword
tommy.color('black')
tommy.left(45)
tommy.forward(8)
tommy.right(90)
tommy.forward(8)
tommy.right(45)
tommy.forward(10)
tommy.right(45)
tommy.forward(8)
tommy.right(90)
tommy.forward(8)
tommy.end_fill()
tommy.left(45)
tommy.penup()
tommy.goto(0,135)
tommy.left(270)
tommy.pendown()
tommy.begin_fill()
#draw half of blade
tommy.color('silver')
tommy.left(225)
tommy.forward(20)
tommy.left(45)
tommy.forward(225)
tommy.left(90)
tommy.forward(15)
tommy.end_fill()
tommy.goto(0,135)
tommy.pendown()
tommy.right(45)
tommy.begin_fill()
#draw other half of blade
tommy.color('dimgrey')
tommy.forward(20)
tommy.right(45)
tommy.forward(225)
tommy.right(90)
tommy.forward(15)
tommy.end_fill()
tommy.right(90)
tommy.color('red')
tommy.forward(210)
tommy.penup()
tommy.right(90)
tommy.forward(6)
tommy.right(90)
tommy.forward(227)
#draw hilt design
tommy.color('gold')
tommy.pendown()
tommy.right(90)
tommy.forward(10)
tommy.left(135)
tommy.forward(14)
tommy.left(135)
tommy.forward(10)
tommy.left(135)
tommy.forward(14)
tommy.right(135)
tommy.forward(10)
tommy.left(180)
tommy.forward(20)
tommy.left(135)
tommy.forward(14)
tommy.left(135)
tommy.penup()
tommy.forward(10)
tommy.pendown()
tommy.left(135)
tommy.forward(14)
tommy.penup()
tommy.right(135)
tommy.forward(10)
tommy.pendown()
tommy.left(90)
tommy.forward(10)
tommy.left(135)
tommy.forward(14)
tommy.left(135)
tommy.penup()
tommy.forward(10)
tommy.pendown()
tommy.left(135)
tommy.forward(14)
tommy.left(135)
tommy.forward(20)
tommy.left(180)
tommy.forward(20)
tommy.right(45)
tommy.forward(14)
tommy.right(135)
tommy.forward(10)
tommy.right(135)
tommy.forward(15)
tommy.left(135)
tommy.forward(10)
tommy.left(180)
tommy.forward(20)
tommy.right(135)
tommy.forward(15)
tommy.left(135)
tommy.forward(10)
tommy.left(135)
tommy.forward(15)
tommy.right(135)
tommy.forward(20)
tommy.right(135)
tommy.forward(15)
tommy.left(135)
tommy.forward(10)
tommy.left(135)
tommy.forward(15)
tommy.penup()
tommy.goto(75,135)



#writes name
tommy.write('Kadin Terronez',font=("Arial", 16, "normal")) # signs your name to your art
turtle.exitonclick() #Keeps pycharm window open so we can see the drawing
